---
  # Play1 - WebServer related tasks
  ##Ad-hoc
  ##ansible -i hosts all -m yum -a 'name=ncdu state=present'
  - name: Play Web - Create apache directories and username in web servers
    hosts: remote
    become: yes
    become_user: root
    vars:
       username: itmunk
       home_dir: /home/itmunk
       usergroup: itmunk
       app_name: httpd
    tasks:
      - name: create username itmunk
        user:
          name: "{{username}}"
          group: "{{usergroup}}"
          shell: /bin/bash
          home: "{{home_dir}}"

      - name: install httpd
        yum:
          name: "{{app_name}}"
          state: installed
     