---
## Play-1: Webserver related tasks

##Ad-hoc command
##ansible -i hosts all -m yum -a 'name=httpd state=present'

- name: Create apache dirs and usernames
  hosts: all
  become: yes
  become_user: root
  roles:
    - httpd
